spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create create-drop update none	
logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.evaitcsmatt.bookhub.webserver: DEBUG  # Your package name
    org.springframework.web: DEBUG  # For web request logging
    org.springframework.security: DEBUG  # For security debugging
    org.springframework.transaction: DEBUG  # For transaction debugging
jwt:
	secret: JLidcJbhdHal98ce2hVC7w8HEd4Cx//khkGRKlb3Gro=
