spring:
  datasource:
    url: jdbc:h2:mem:bookhubdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop #create create-drop update none

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.evaitcsmatt.bookhub.webserver: INFO  
    org.springframework.web: WARN 
    org.springframework.security: WARN 
    org.springframework.transaction: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

jwt:
  secret: JLidcJbhdHal98ce2hVC7w8HEd4Cx//khkGRKlb3Gro=